### ISSUE TITLE
Thermal Expansion induction smelter broken

### ISSUE THREAD

**Issue by G2159687** [ICannt/Netherending-Ores#1]
I've found Thermal Expansion's induction smelter recipe has changed because of this mod.

For example, the smelter can originally use **1 gold ore** + **1 sand** to produce **2 gold ingots**,
but it changed to **2 gold ores** + **1 sand** to produce **2 gold ingots** after adding the mod, like the [screenshot](https://imgur.com/a/SEi2Z) shows.

This makes the induction smelter completely unusable, please fix the problem. Thanks!

**Comment by LiamEarle** [comment]
Hi G2159687,

Thanks for your issue report. I’ll try and replicate the issue to see if anything on our end is not playing nicely with Thermal Expansion.

Would you please be able to supply us with your mod list displaying the version of each mod so we can test?

**Comment by G2159687** [comment]
OK. All the mods I installed: https://imgur.com/a/LtITr
All the mods should be the latest stable version.

**Comment by G2159687** [comment]
And Forge version 14.23.1.2555.

**Comment by G2159687** [comment]
Hmm... And an additional thing, the cobalt ore and ardite ore are working normally. Hope this information helps.

**Comment by G2159687** [comment]
CoFH's mods has been updated, but the problem still exists :( 

Did you replicated this problem successfully @LiamEarle ?

**Comment by LiamEarle** [comment]
Hey again,

Haven’t had a chance to look at it over Christmas but when I get a free moment I’ll do some experimenting and get back to you with the findings!

Thanks for your patience!

**Comment by G2159687** [comment]
OK. Thank you for replying and sorry for my impatience!

Besides, here's updated mod list: https://imgur.com/a/1nlOQ

**Comment by trabpukcip** [comment]
The mod contains no recipes that directly furnace Gold Ore as an input only the mods own ores are furnaced. The code is also really simple. Some bizarre ore dictionary matching is taking place to cause this. I would suggest correcting the recipes with ModTweaker until myself or Liam gets to the bottom of it.

**Comment by G2159687** [comment]
Ok, now I'm writing scripts to correct them. By the way, writing scripts is boring :P 

Can I post the script to curseforge when I finish writing it? Maybe it can help more people dealing with the problem.

And I can help translating the mod into Simplified Chinese (zh_CN), please tell me if you would like to add Chinese translation :)

**Comment by trabpukcip** [comment]
Fixed in 1.1.1 (will be on curseforge when they approve it).

This also affected the Pyro-Concentrator, the issue could have affected any ore output with something that does Ore Dictionary lookups as it was setting the count to 2 wherever it was being used.

Now only gets the item and metadata from the Ore Dictionary ItemStack and makes a new ItemStack with the correct count of 2.

Blame me :P

Note: You are most welcome to make a translation for Simple Chinese (zn_cn.lang), just make a Gist for it or a pull request with the latest fork update once done (there is a Russian translation I need to add too).
Also please update your mods, some are now out of date and that version of CoFH World is definitely out of date and appears to have been pulled from distribution on Curseforge, I got it from some dodgy Russian site....

**Comment by G2159687** [comment]
Thanks for fixing the bug! I was having trouble correcting Tinker Construct's melting recipes by writing scripts, and now I don't need to deal with it anymore. The melting recipes is also fixed :)

About CoFH World's version, I just noticed CoFH World's another update after posting my updated mod list... Sorry about that.

And Gist for zh_cn.lang: https://gist.github.com/G2159687/52f7224f2af21aac27b9cf64aee58b94
