### ISSUE TITLE
Mob Support & Detonating Ores

### ISSUE THREAD

**Issue by NielsPilgaard** [ICannt/Netherending-Ores#2]
Hey!

I'd love a feature that enrages nearby pigmen when nether ores are mined, optionally with a chance config. Would that be doable?

Thanks for the mod :)

**Comment by trabpukcip** [comment]
I have thought about this since I first started the mod, plus having the exploding ores as well.
Also had discussions about spawning endermites for the end ores.

Unfortunately I don't have the time to dedicate to adding these features at the moment and will be sticking to only fixing bugs and adding new ores (if requested).

I do plan to port this to 1.13 when it drops so I will look into it then.

**Comment by trabpukcip** [comment]
I think I am going to try to do this in a 1.12 release in the near future.

**Comment by trabpukcip** [comment]
Some progress from the Mob Test repo: [https://github.com/ICannt/Mob-Test](url)
![Netherfish](https://i.imgur.com/hHVaYJC.png)

**Comment by poulhp** [comment]
Is this still being worked on?

**Comment by trabpukcip** [comment]
Not at the moment.
