### ISSUE TITLE
All Ores in Thermal Machines produce less overall

### ISSUE THREAD

**Issue by Mario90900** [ICannt/Netherending-Ores#21]
When you try to process any of the ores in Thermal Expansion machines, in the furnace, induction smelter, or the pulverizer, you end up getting less output then what seems to be intended? If you smelt any of the ores in the powered furnace, you only get a single overworld ore as output; while if you used a vanilla furnace or an Ender IO alloy smelter, you end up getting two overworld ores. The same case seems to be for most of the pulverizer recipes as well, and some appear to be missing Ender IO sag mill recipes, though I'm not sure I see a pattern with some of these. I figured I would make an issue in case some of this wasn't intended!

**Comment by trabpukcip** [comment]
This is intended behaviour. It is designed so that output is not excessive when augments are used. Augments cannot be ignored on recipe input by Thermal Expansion's design, so this mod is designed around them. This behaviour can be overridden in the config file if you like lots of ore with the augments, or the augments that boost output have been disabled recipe wise.

The reason that sag mill recipes would be missing is that Ender IO is not actually supported API wise by the mod. Any recipes that do come up, Ender IO has probably added them from another mods recipes or even another mod adding its recipes to Ender IO. I have no control over this.

Ender IO support was not initially done as when I was working on API's back in 2017, Ender IO was not even ported to 1.12.2 yet. I will get around to proper full support one day, which would result in consistent recipes.

**Comment by Mario90900** [comment]
Aah, thank you very much for this explanation. Also thank you for already having those configs added as well! I am unsure how EIO got a recipe for sag milling coal, but it seems likely they just utilize the vanilla recipes for the furnace mode of the smelter. Either way, I do look forward to any future integration with more mods!
